"""Base provider abstract class for LLM chat interfaces.

This module defines the interface that all LLM providers must implement,
ensuring consistent behavior across different backend services.
"""

import requests
from abc import ABC, abstractmethod
from typing import Any


class BaseProvider(ABC):
    """Abstract base class for all LLM provider implementations.

    This class defines the common interface and methods that all providers
    (local or cloud-based) must implement to ensure consistent integration
    with the Gradio chat application.

    Attributes:
        config (dict): Configuration dictionary containing provider-specific settings.
        provider_type (str): Identifier string for the provider type.
    """

    def __init__(self, config: dict[str, Any]) -> None:
        """Initialize the provider with configuration parameters.

        Args:
            config: Dictionary containing provider-specific configuration
                   such as endpoint URL, model name, authentication credentials, etc.
        """
        self.config = config
        self._validate_config()

    @abstractmethod
    def _validate_config(self) -> None:
        """Validate the provider configuration parameters.

        This method should check that all required configuration fields are present
        and have valid values. Raises ValueError if validation fails.

        Raises:
            ValueError: If configuration is invalid or missing required fields.
        """
        pass

    @abstractmethod
    def stream_chat(self, messages: list[dict[str, str]]) -> Any:
        """Generate a streaming response for the given chat history.

        This method should yield partial responses as they are generated by
        the LLM, allowing for real-time display in the Gradio interface.

        Args:
            messages: List of message dictionaries with 'role' and 'content' keys.
                     Format: [{"role": "user", "content": "..."}, ...]

        Yields:
            Partial response content or complete message dictionaries that can be
            displayed in the chatbot component.

        Raises:
            ConnectionError: If unable to connect to the provider endpoint.
            ValueError: If request parameters are invalid.
            RuntimeError: If an unexpected error occurs during inference.
        """
        pass

    @abstractmethod
    def get_provider_type(self) -> str:
        """Return the identifier string for this provider type.

        Returns:
            String identifier for the provider (e.g., "lmstudio", "llamacpp").
        """
        pass

    @abstractmethod
    def fetch_models(self) -> list[str]:
        """Fetch available models from the provider endpoint.

        This method should query the provider's API to retrieve a list of
        available model identifiers that can be used for chat completions.

        Returns:
            List of model names/identifiers (e.g., ['model-1', 'model-2']).
            Empty list if no models are found or endpoint doesn't support listing.

        Raises:
            ConnectionError: If unable to connect to the provider endpoint.
            RuntimeError: If the response is invalid or unexpected format.
            requests.Timeout: If the request times out (default: 10 seconds).
        """
        pass

    def get_config_field_names(self) -> list[str]:
        """Return a list of configuration field names for UI rendering.

        This method can be overridden by subclasses to provide custom field names
        for the dynamic configuration panel in the Gradio interface.

        Returns:
            List of configuration field names that should be displayed in the UI.
        """
        return ["endpoint_url", "model_name"]

    def get_config_defaults(self) -> dict[str, str]:
        """Return default values for configuration fields.

        This method can be overridden by subclasses to provide sensible defaults
        for their specific configuration requirements.

        Returns:
            Dictionary mapping field names to their default values.
        """
        return {}
